### ISSUE TITLE
Possibility of switching focus to IDA from pycharm?

### ISSUE THREAD

**Issue by Uzver123** [overfl0/IDAPython-pycharm-setup#6]
I found myself in very confusing situation i have two screens one has PyCharm other Ida Pro when i run PyCharm script that ask for user input i see user input box pop up on the second screen and start typing or paste value and it goes into the PyCharm window because focus is not set to Ida Pro window.

I know its totally user fault, but my mind is very used to think if there's a popup window appears on my computer it usually already has focus, which is not the case here.

Is there way to focus Ida Window from PyCharm script somehow? 

Perhaps easiest way would be to focus Ida window before showing the user input box.

**Comment by overfl0** [comment]
> Is there way to focus Ida Window from PyCharm script somehow?

I have never done this, but quick googling suggests that using
```python
win32gui.SetForegroundWindow(hwnd)
```
might do the trick.

**Comment by Uzver123** [comment]
Forget about power of python lol, thought switching has to be made trough wrapper code...

```
import win32gui

hwnd = win32gui.FindWindow(None, "Calculator")

if hwnd:
    win32gui.SetForegroundWindow(hwnd)
```
That works, not ideal though as ida title is long and tricky to type by hand, have to use tool like [WinSpy](https://github.com/strobejb/winspy) to copy window title, which is too many steps, need to use partial window title, will share alternative solution once i find it.
