### ISSUE TITLE
make python script file name dynamic?

### ISSUE THREAD

**Issue by Uzver123** [overfl0/IDAPython-pycharm-setup#7]
Right now when setting up have to provide script filename in, so every time i run wrapper it loads temp.py file, how to setup so it sends to wrapper the currently open file instead of temp.py?

![image](https://github.com/overfl0/IDAPython-pycharm-setup/assets/143356096/5cab9d81-ad59-425c-afc7-ae02a8091b09)

**Comment by overfl0** [comment]
If you have set up the template correctly, by clicking `Edit configurations templates...` at the bottom left of your screenshot (also visible in the readme), you don't have to set anything else up, you just select "run" (or use the keyboard shortcut to do that) and it will reuse the same setup for the current file that you have open.

**Comment by Uzver123** [comment]
That's right i was confused because `interpreter options` input box become so little in new version.

![image](https://github.com/overfl0/IDAPython-pycharm-setup/assets/143356096/4646249c-6045-4eee-99be-36212aba6e1d)
